Update documentation
SUSE-Enceladus/cloud-netconfig pull request #13
Opened 2021-04-20 13:12 UTC by jgleissner

Include GCE in supported platforms.
Adjust documentation to reflect behavior changes, namely routing policies also for main interface and no removal of addresses it didn't add.
Add info about systemd timer.
Add info about CLOUD_NETCONFIG_MANAGE default variable.
Add more detail about mode of operation.

2021-04-20 15:49 UTC, aosthof requested changes
Easy to read and understandable, LGTM aside from the 3 typos.

2021-04-20 15:49 UTC, aosthof commented on README.md
> +wicked.serice` on SUSE Linux Enterprise Server or openSUSE distributions).  On
Typo: wicked.ser_v_ice

2021-04-20 15:49 UTC, aosthof commented on README.md
> +IPv4 addresses from the framework's metadta server and configure them on the
Typo: metad_a_ta

2021-04-20 15:49 UTC, aosthof commented on README.md
> +also change the default value of **CLOUD__NETCONFIG__MANAGE** for in
Obsolete word "for".

2021-04-21 08:20 UTC, jgleissner commented on README.md
> +also change the default value of **CLOUD__NETCONFIG__MANAGE** for in
Thanks for proofreading, typos fixed.

2021-04-21 14:09 UTC, merged